Add tox for tests
Enable tox and clean up for lightweight tests.

- Enable tox, testing, formatting and linting for all supported versions of
  Python
- Clean out unused imports and replace wildcard imports with explicit
  imports

I encountered this error on running tox:

```
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you
mean: 'zipimporter'?
```

The fix was to replace my tox venv with a new one built from a recent
version of Python and install it with an fresh installation of pipx.